services:
  web:
    build: .
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    volumes:
      - /dev/shm:/dev/shm
