name: Ping Service

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service to keep it alive
        run: |
          curl -X GET https://pewterfelt-ai.onrender.com/api/ping
