name: Ping Service

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping service to keep it alive
        run: |
          curl -X GET -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" https://pewterfelt-ai.onrender.com/api/ping
